### ISSUE TITLE
doc: documentation improvements for milestone 0.0.1

### ISSUE THREAD

**Issue by neurodiff** [ekotik/sh.wrap#41]
### Description

User, developers, planning documentation improvements for milestone 0.0.1.

### A list of goals

- [ ] "Getting started" page is created with information how to get and install sh.wrap
- [ ] "Usage" page is created with information how to use sh.wrap
- [x] Development, planning and user documentations are moved to their own sections
