### ISSUE TITLE
project: project improvements for milestone 0.0.1

### ISSUE THREAD

**Issue by neurodiff** [ekotik/sh.wrap#47]
### Description

Project management tasks and improvements for milestone 0.0.1.

### A list of goals

- [ ] sh.wrap purpose and vision is described in Project documentation section
- [ ] Milestone 0.1.0 created with selected/estimated/scheduled tasks
- [ ] Roadmap updated for Milestone 0.1.0
- [x] Roadmap diagram created
